%YAML 1.1
---
# yaml-language-server: $schema=./schema.default.json

data:
  cutout:
    source: build
    version: unknown

atlite:
  default_cutout: "europe-2015-sarah3-era5"
  nprocesses: 1
  show_progress: false
  plot_availability_matrix: false

  cutouts:
    "europe-2015-sarah3-era5":
      module: era5
      x:
      - -12.0
      - 42.0
      y:
      - 33.0
      - 72.0
      dx: 0.3
      dy: 0.3
      time:
      - "2015"
      - "2015"
      chunks:
        time: 500
      prepare_kwargs:
        features:
        - wind
        - influx
        - temperature
        - height
        - runoff
        monthly_requests: true
        tmpdir: ./cutouts_tmp/
